config/routes.rb
Rails.application.routes.draw do

  root to: 'urls#index'

  resources :urls

  get '/api_page' => 'urls#api_page'
  get '/:shorty' => 'urls#out_url'

end

app/models/url.rb
class Url < ActiveRecord::Base
  require "net/http"

  before_validation :generate_shorty
  validates :original_url, presence: true, format: {with: URI::regexp(%w(http https)), message: "URL must start with http:// or https://"}, uniqueness: {case_sensitive:false}
  validates :shorty, uniqueness: true, presence: true

  private

  def generate_shorty
    if self.new_record? && url_exist?
      begin
        var = Time.now.to_s
        self.shorty = Digest::MD5.hexdigest(var).slice(0..6)
      end while self.class.exists?(shorty: shorty)
    end
  end

  def url_exist?
    begin
      url = URI.parse(original_url)
      req = Net::HTTP.new(url.host, url.port)
      p (url.scheme == 'https')
      req.use_ssl = (url.scheme == 'https')
      path = url.path if url.path.present?
      res = req.request_head(path || '/')
      res.code != "404"
    rescue => e
      p e.inspect
      errors.add(:original_url, "Problem with the original_url")
      return false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  def add_page_number_size
    unless params[:page]
      params[:page] = 1
      params[:size] = 10
    end
  end

end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:show, :edit, :update, :destroy]
  before_action :add_page_number_size, only: [:index]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.paginate(:page => params[:page].to_i, :per_page => params[:size])
    respond_to do |format|
      format.html
      format.json {render json: @urls}
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render json: @url}
    end
    # render json: @url
  end

  # GET /urls/new
  def new
    @url = Url.new
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully shortened.' }
        format.json { render json: @url, status: :created }
        # render json: short_url, status: :created
      else
        format.html { render :new }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { render json: @url, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url, notice: 'Url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def out_url
    url = Url.find_by_shorty(params[:shorty])
    if url
      redirect_to url.original_url
    else
      render json: {errors: {message: "Couldn't find the data"}}, status: 204
    end
  end

  def api_page
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:original_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="pull-right">
      <%= link_to root_url, class: "btn btn-primary btn-md", style: "color:white;" do %>
        <span class="glyphicon glyphicon-home"></span> Home
      <% end %>
      <%= link_to api_page_path, class: "btn btn-primary btn-md", style: "color:white;" do %>
        <span class="glyphicon glyphicon-home"></span> API Guide
      <% end %>
    </div>
    <%= yield %>
  </div>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div class="alert alert-warning">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.text_field :original_url, class: "form-control", placeholder: "Original URL" %>
      </div>
    </div>
    <div class="col-md-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/urls/api_page.html.erb
<div class="row" style="padding:20px;">
  <h2>URL shortener API</h2><br/>
  <h2>API Request</h2>
  <p>
    <h3>Listing the URLs</h3>
     url: <%= root_url %>urls.json<br/>
     method: GET<br/>
  </p>
  <p>
    <h3>Retrieving URL detail</h3>
    url: <%= root_url %>urls/:id.json<br/>
    method: GET<br/>
  </p>
  <p>
    <h3>Deleting URL</h3>
    url: <%= root_url %>urls/:id.json<br/>
    method: DELETE<br/>
  </p>
  <p>
    <h3>Updating URL</h3>
    url: <%= root_url %>urls/:id.json<br/>
    method: PATCH
  </p>
  <p>
    <h3>Creating URL</h3>
    url: <%= root_url %>urls.json<br/>
    method: POST<br/>
  </p>
  <p>
    <h3>redirect_to original_url:</h3> <%= root_url %>shorty.json
  </p>
  <hr/>
  <h2>To test from console</h2>
  <p>
      <h3>index:</h3>
        curl -X GET <%= root_url %>urls.json<br/>
        <h4>OR</h4>
        curl -X GET --data "page=1&size=10" <%= root_url %>urls.json
        <br/><br/>
        <h4>Note:</h4>page number or size parameters if nil defaults to 1 & 10 respectively
        And returns the paginated result with next and previous links.
  </p>
  <p>
      <h3>show:</h3> curl -X GET <%= root_url %>urls/:id.json
  </p>
  <p>
      <h3>destroy:</h3>
        curl -X DELETE <%= root_url %>urls/:id.json
  </p>
  <p>
      <h3>update:</h3>
        curl -X PATCH --data "url[original_url]=http://www.url.com/index" <%= root_url %>urls/:id.json
  </p>
  <p>
      <h3>create:</h3>
        curl -X POST --data "url[original_url]=http://www.url.com/index" <%= root_url %>urls.json
  </p>
  <p>
      <h3>redirect_to original_url:</h3>
        curl -X GET <%= root_url %>shorty.json
  </p>
</div>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/index.html.erb
<div class="row">
  <div class="col-md-2"><h1>URLs</h1></div>
  <div class="col-md-2" style="margin-top: 20px;margin-bottom: 10px;">
    <%= link_to new_url_path, class: "btn btn-primary btn-md", style: "color:white;" do %>
      <span class="glyphicon glyphicon-plus-sign"></span> New Url
    <% end %>
  </div>
</div>
<br/>
<table class="table table-inverse" style="table-layout:fixed;">
  <thead>
    <tr>
      <th class="col-md-6">Original url</th>
      <th class="col-md-3">Shorty</th>
      <th class="col-md-3">Operations</th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td style="display: block;overflow: hidden;text-overflow: ellipsis;"><%= url.original_url %></td>
        <td><%= url.shorty %></td>
        <td><%= link_to 'Show', url %> | <%= link_to 'Edit', edit_url_path(url) %> | <%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="digg_pagination" style="text-align:center;">
  <div class="page_info">
    <%= page_entries_info @urls %>
  </div>
  <%= will_paginate @urls, :container => false %>
</div>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

app/views/urls/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-inverse">
  <thead>
    <tr>
      <th>Original url</th>
      <th>Shorty</th>
      <th>Operations</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="word-wrap:break-word;word-break:break-all;"><%= @url.original_url %></td>
      <td><%= @url.shorty %></td>
      <td><%= link_to 'Edit', edit_url_path(@url) %> | <%= link_to 'Back', urls_path %></td>
    </tr>
  </tbody>
</table>